### ISSUE TITLE
MKL benchmarking for real out-of-place is not correctly configured 

### ISSUE THREAD

**Issue by raphael-egan** [intel/double-batched-fft-library#11]
In case `M = 1`, [this line](https://github.com/intel/double-batched-fft-library/blob/5b69fc80084967ae90b70e45f424b2ce19d76ac7/benchmark/mkl_descriptor.hpp#L24) is correct for in-place problems but it should read
`plan->set_value(oneapi::mkl::dft::config_param::FWD_DISTANCE, N * M);` for **out-of-place** real problems.

**Comment by uphoffc** [comment]
Fixed in v0.4.0
