### ISSUE TITLE
Spack package?

### ISSUE THREAD

**Issue by colleeneb** [intel/double-batched-fft-library#8]
Hello,

Is there any chance a spack package of this could be made? I'm asking since we had a request to install it, and a spack package would be more convenient for us. No problem if this isn't possible, we just wanted to ask in case.

Thanks!

**Comment by uphoffc** [comment]
Hi Colleen,

I already have a prototype for a spack package. I just need clarify some technical details, in particular how to best model the sycl dependency.

Best regards,
Carsten

**Comment by colleeneb** [comment]
Thank you!

Colleen

**Comment by uphoffc** [comment]
A spack package is now available in the develop version of spack. https://github.com/spack/spack/pull/36086
