### ISSUE TITLE
Preferred short name for the project

### ISSUE THREAD

**Issue by al42and** [intel/double-batched-fft-library#9]
Hello!

This repo name, CMakeLists.txt, and the docs refer to this project as "Double-Batched FFT", which is fine, but a bit of a mouthful, especially compared to other library names (cuFFT, VkFFT, oneMKL, ...). This can be problematic when using the name on plots or in tables or simply when referring to it in documentation for an external project.

The filenames and namespace uses `bbfft`, which is also fine but has some problems:

- it's not obvious that "bb fft" and "double-batched fft" refer to the same thing,
- it's unclear how to capitalize it  (BBFFT? bbfft? bbFFT?) since the code imposes its style.

Could you please advise on whether there is a recommended shorthand for referring to the project?

**Comment by uphoffc** [comment]
Hi!

The product name is "Double-Batched FFT Library" and there is no official abbreviation or shorthand. If you need an abbreviation for technical reasons I suggest to always introduce it in the beginning of the article, report, or documentation. I would advise against introducing the abbreviation "DBFFT" as there is already an unrelated paper that has DBFFT in its title. Personally, I prefer all-lowercase or all-uppercase for abbreviations as I find mixed-case strings harder to remember.

Best regards,
Carsten

**Comment by al42and** [comment]
To summarize, something like "Double-Batched FFT Library (BBFFT)" in the intro, and "BBFFT" later would be fine, right?

**Comment by uphoffc** [comment]
Yes, that's fine.

**Comment by al42and** [comment]
Great, thanks.

Should this issue be closed, or kept open in case others face the same question?

**Comment by uphoffc** [comment]
I think I can close it and pin it.
